models:
  - type: main
    engine: ollama
    model: wizard-vicuna-uncensored:7b
    parameters:
      base_url: http://10.1.25.121:11434

  - type: embeddings
    engine: FastEmbed
    model: all-MiniLM-L6-v2


instructions:
  - type: general
    content: |
      You are a chatbot assistant. Answer to the given message:

prompts:
  - task: general
    content: |-
      {{ general_instructions }}

      {{ history | user_assistant_sequence }}
      Assistant:


